defaults: &defaults
  working_directory: ~/clark-taxonomy
  docker:
    - image:  circleci/node:11

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Package
          command: npm run build
      - run:
          name: Run Unit Tests
          command: npm test
      - persist_to_workspace:
          root: ./
          paths: 
            - ./package.json
            - ./dist
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/clark-taxonomy
      - run:
          name: Expose NPM Key
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/clark-taxonomy/.npmrc
      - run:
          name: Publish to NPM
          command: npm publish
workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              ignore: /master/
  build-test-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only: /master/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
              - build
          filters:
            branches:
              only: /master/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/