export const taxonomy = {
  lengths: ['nanomodule', 'micromodule', 'module', 'unit', 'course'],
  taxons: {
    'remember and understand': {
      verbs: [
        'Remember',
        'Understand',
        'Define',
        'List',
        'Record',
        'Repeat',
        'Define',
        'Find',
        'Label',
        'List',
        'Match',
        'Name',
        'Omit',
        'Recall',
        'Relate',
        'Select',
        'Show',
        'Spell',
        'Tell',
        'Describe',
        'Discuss',
        'Explain',
        'Express',
        'Identify',
        'Recognize',
        'Restate',
        'Translate',
        'Classify',
        'Compare',
        'Contrast',
        'Demonstrate',
        'Explain',
        'Extend',
        'Illustrate',
        'Infer',
        'Interpret',
        'Outline',
        'Relate',
        'Rephrase',
        'Show',
        'Summarize',
        'Translate'
      ]
    },
    'apply and analyze': {
      verbs: [
        'Apply',
        'Demonstrate',
        'Dramatize',
        'Employ',
        'Illustrate',
        'Interpret',
        'Operate',
        'Practice',
        'Schedule',
        'Shop',
        'Sketch',
        'Use',
        'Apply',
        'Build',
        'Construct',
        'Develop',
        'Experiment with',
        'Identify',
        'Interview',
        'Make use of',
        'Model',
        'Organize',
        'Plan',
        'Select',
        'Solve',
        'Utilize',
        'Appraise',
        'Calculate',
        'Compare',
        'Contrast',
        'Criticize',
        'Debate',
        'Diagram',
        'Differentiate',
        'Distinguish',
        'Experiment',
        'Inspect',
        'Inventory',
        'Question',
        'Relate',
        'Test',
        'Analyze',
        'Assume',
        'Categorize',
        'Classify',
        'Compare',
        'Conclude',
        'Contrast',
        'Discover',
        'Dissect',
        'Distinguish',
        'Divide',
        'Examine',
        'Function',
        'Inference',
        'Inspect',
        'List',
        'Motive',
        'Relate',
        'Simplify',
        'Survey',
        'Take part in',
        'Test for',
        'Theme',
        'Guided discovery',
        'Observation',
        'Guided participation',
        'Strategy instruction',
        'Direct explanation',
        'Dyadic instruction',
        'Self-instructional training'
      ]
    },
    'evaluate and synthesize': {
      verbs: [
        'Synthesize',
        'Appraise',
        'Assess',
        'Compare',
        'Estimate',
        'Judge',
        'Measure',
        'Rate',
        'Revise',
        'Score',
        'Select',
        'Value',
        'Agree',
        'Appraise',
        'Assess',
        'Award',
        'Compare',
        'Conclude',
        'Criteria',
        'Criticize',
        'Decide',
        'Deduct',
        'Defend',
        'Determine',
        'Disprove',
        'Estimate',
        'Evaluate',
        'Explain',
        'Interpret',
        'Judge',
        'Justify',
        'Mark',
        'Measure',
        'Opinion',
        'Perceive',
        'Prioritize',
        'Prove',
        'Rate',
        'Recommend',
        'Rule on',
        'Select',
        'Support',
        'Value',
        'Arrange',
        'Collect',
        'Compose',
        'Construct',
        'Create',
        'Design',
        'Formulate',
        'Manage',
        'Organize',
        'Plan',
        'Prepare',
        'Propose',
        'Set up',
        'Adapt',
        'Build',
        'Change',
        'Combine',
        'Compile',
        'Compose',
        'Construct',
        'Create',
        'Delete',
        'Design',
        'Develop',
        'Discuss',
        'Elaborate',
        'Estimate',
        'Formulate',
        'Imagine',
        'Improve',
        'Invent',
        'Make up',
        'Maximize',
        'Minimize',
        'Modify',
        'Originate',
        'Plan',
        'Predict',
        'Propose',
        'Solve',
        'Suppose',
        'Test',
        'Theorize',
        'Code',
        'Debug',
        'Implement'
      ]
    }
  }
};
