export const taxonomy = {
    'lengths': [
        'Nanomodule',
        'Micromodule',
        'Module',
        'Unit',
        'Course'
    ],
    'taxons': {
        'Remember and Understand': {
            'verbs': [
                'Choose',
                'Classify',
                'Compare',
                'Contrast',
                'Define',
                'Demonstrate',
                'Describe',
                'Discuss',
                'Explain',
                'Express',
                'Extend',
                'Find',
                'Identify',
                'Illustrate',
                'Infer',
                'Interpret',
                'Label',
                'List',
                'Match',
                'Name',
                'Omit',
                'Outline',
                'Recall',
                'Recognize',
                'Record',
                'Relate',
                'Repeat',
                'Rephrase',
                'Restate',
                'Select',
                'Show',
                'Spell',
                'Summarize',
                'Tell',
                'Translate',
            ],
            'assessments': [
                'Case Study',
                'Code Check',
                'Competition',
                'Essay (Quiz/Test)',
                'Essay',
                'Fill in the Blank/Short Answer (Quiz/Test)',
                'Group',
                'Lab',
                'Matching (Quiz/Test)',
                'Multiple Choice (Quiz/Test)',
                'Open-Response (Quiz/Test)',
                'Oral Presentation',
                'Project',
                'Research Paper',
                'True/False Questions'
            ],
            'quizzes': [
                'Essay',
                'Fill in the Blank/Short Answer',
                'Matching',
                'Multiple Choice',
                'Open-Response',
                'True/False Questions'
            ],
            'strategies': [
                'Advanced organizers',
                'Analogies',
                'Assessment',
                'Audio',
                'Chunking',
                'Classification',
                'Concept mapping',
                'Discussion',
                'Elaboration',
                'Examples',
                'Illustrations',
                'Imagery',
                'Learner',
                'Lecture',
                'Metaphoric techniques',
                'Mnemonics',
                'Presentations',
                'Questions',
                'Rehearsal',
                'Reports',
                'Review',
                'Test',
                'Video',
                'Visuals',
                'Writing'
            ]
        },
        'Apply and Analyze': {
            'verbs': [
                'Analyze',
                'Apply',
                'Appraise',
                'Assume',
                'Build',
                'Calculate',
                'Categorize',
                'Choose',
                'Classify',
                'Compare',
                'Conclude',
                'Construct',
                'Contrast',
                'Criticize',
                'Debate',
                'Demonstrate',
                'Develop',
                'Diagram',
                'Differentiate',
                'Direct explanation',
                'Discover',
                'Dissect',
                'Distinguish',
                'Divide',
                'Dramatize',
                'Dyadic instruction',
                'Employ',
                'Examine',
                'Experiment with',
                'Experiment',
                'Function',
                'Guided discovery',
                'Guided participation',
                'Identify',
                'Illustrate',
                'Inference',
                'Inspect',
                'Interpret',
                'Interview',
                'Inventory',
                'List',
                'Make use of',
                'Model',
                'Motive',
                'Observation',
                'Operate',
                'Organize',
                'Plan',
                'Practice',
                'Question',
                'Relate',
                'Schedule',
                'Select',
                'Self-instructional training',
                'Shop',
                'Simplify',
                'Sketch',
                'Solve',
                'Strategy instruction',
                'Survey',
                'Take part in',
                'Test for',
                'Test',
                'Theme',
                'Use',
                'Utilize'
            ],
            'assessments': [
                'Case Study',
                'Code Check',
                'Competition',
                'Essay (Quiz/Test)',
                'Essay',
                'Fill in the Blank/Short Answer (Quiz/Test)',
                'Group',
                'Lab',
                'Multiple Choice (Quiz/Test)',
                'Open-Response (Quiz/Test)',
                'Oral Presentation',
                'Project',
                'Research Paper'
            ],
            'quizzes': [
                'Essay',
                'Fill in the Blank/Short Answer',
                'Multiple Choice',
                'Open-Response'
            ],
            'strategies': [
                'Case Studies',
                'Critical Incidents',
                'Demonstrations',
                'Discussion',
                'Exercises',
                'Microteach',
                'Practice',
                'Problems',
                'Projects',
                'Questions',
                'Role Play',
                'Simulations',
                'Sketches',
                'Test'
            ]
        },
        'Evaluate and Synthesize': {
            'verbs': [
                'Adapt',
                'Agree',
                'Appraise',
                'Arrange',
                'Assess',
                'Award',
                'Build',
                'Change',
                'Choose',
                'Code',
                'Collect',
                'Combine',
                'Compare',
                'Compile',
                'Compose',
                'Conclude',
                'Construct',
                'Create',
                'Criteria',
                'Criticize',
                'Debug',
                'Decide',
                'Deduct',
                'Defend',
                'Delete',
                'Design',
                'Determine',
                'Develop',
                'Discuss',
                'Disprove',
                'Elaborate',
                'Estimate',
                'Evaluate',
                'Explain',
                'Formulate',
                'Imagine',
                'Improve',
                'Interpret',
                'Invent',
                'Judge',
                'Justify',
                'Make up',
                'Manage',
                'Mark',
                'Maximize',
                'Measure',
                'Minimize',
                'Modify',
                'Opinion',
                'Organize',
                'Originate',
                'Perceive',
                'Plan',
                'Predict',
                'Prepare',
                'Prioritize',
                'Propose',
                'Prove',
                'Rate',
                'Recommend',
                'Revise',
                'Rule on',
                'Score',
                'Select',
                'Set up',
                'Solve',
                'Support',
                'Suppose',
                'Test',
                'Theorize',
                'Value'
            ],
            'assessments': [
                'Case Study',
                'Code Check',
                'Competition',
                'Essay (Quiz/Test)',
                'Essay',
                'Group',
                'Lab',
                'Open-Response (Quiz/Test)',
                'Oral Presentation',
                'Project',
                'Research Paper'
            ],
            'quizzes': [
                'Essay',
                'Open-Response'
            ],
            'strategies': [
                'Appraisals',
                'Case Studies',
                'Constructs',
                'Creative Exercises',
                'Critiques',
                'Develop Plans',
                'Exercises',
                'Problems',
                'Projects',
                'Simulations'
            ]
        }
    }
}