export const taxonomy = {
  lengths: ['nanomodule', 'micromodule', 'module', 'unit', 'course'],
  taxons: {
    'remember and understand': {
      verbs: [
        'remember',
        'understand',
        'define',
        'list',
        'record',
        'repeat',
        'define',
        'find',
        'label',
        'list',
        'match',
        'name',
        'omit',
        'recall',
        'relate',
        'select',
        'show',
        'spell',
        'tell',
        'describe',
        'discuss',
        'explain',
        'express',
        'identify',
        'recognize',
        'restate',
        'translate',
        'classify',
        'compare',
        'contrast',
        'demonstrate',
        'explain',
        'extend',
        'illustrate',
        'infer',
        'interpret',
        'outline',
        'relate',
        'rephrase',
        'show',
        'summarize',
        'translate'
      ]
    },
    'apply and analyze': {
      verbs: [
        'apply',
        'demonstrate',
        'dramatize',
        'employ',
        'illustrate',
        'interpret',
        'operate',
        'practice',
        'schedule',
        'shop',
        'sketch',
        'use',
        'apply',
        'build',
        'construct',
        'develop',
        'experiment with',
        'identify',
        'interview',
        'make use of',
        'model',
        'organize',
        'plan',
        'select',
        'solve',
        'utilize',
        'appraise',
        'calculate',
        'compare',
        'contrast',
        'criticize',
        'debate',
        'diagram',
        'differentiate',
        'distinguish',
        'experiment',
        'inspect',
        'inventory',
        'question',
        'relate',
        'test',
        'analyze',
        'assume',
        'categorize',
        'classify',
        'compare',
        'conclude',
        'contrast',
        'discover',
        'dissect',
        'distinguish',
        'divide',
        'examine',
        'function',
        'inference',
        'inspect',
        'list',
        'motive',
        'relate',
        'simplify',
        'survey',
        'take part in',
        'test for',
        'theme',
        'guided discovery',
        'observation',
        'guided participation',
        'strategy instruction',
        'direct explanation',
        'dyadic instruction',
        'self-instructional training'
      ]
    },
    'evaluate and synthesize': {
      verbs: [
        'synthesize',
        'appraise',
        'assess',
        'compare',
        'estimate',
        'judge',
        'measure',
        'rate',
        'revise',
        'score',
        'select',
        'value',
        'agree',
        'appraise',
        'assess',
        'award',
        'compare',
        'conclude',
        'criteria',
        'criticize',
        'decide',
        'deduct',
        'defend',
        'determine',
        'disprove',
        'estimate',
        'evaluate',
        'explain',
        'interpret',
        'judge',
        'justify',
        'mark',
        'measure',
        'opinion',
        'perceive',
        'prioritize',
        'prove',
        'rate',
        'recommend',
        'rule on',
        'select',
        'support',
        'value',
        'arrange',
        'collect',
        'compose',
        'construct',
        'create',
        'design',
        'formulate',
        'manage',
        'organize',
        'plan',
        'prepare',
        'propose',
        'set up',
        'adapt',
        'build',
        'change',
        'combine',
        'compile',
        'compose',
        'construct',
        'create',
        'delete',
        'design',
        'develop',
        'discuss',
        'elaborate',
        'estimate',
        'formulate',
        'imagine',
        'improve',
        'invent',
        'make up',
        'maximize',
        'minimize',
        'modify',
        'originate',
        'plan',
        'predict',
        'propose',
        'solve',
        'suppose',
        'test',
        'theorize',
        'code',
        'debug',
        'implement'
      ]
    }
  }
};
